version: '3.6'

services:
  php:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    container_name: php
    volumes:
    - .:/app
    ports:
      - 80:8000
    networks:
      - devops
  db:
    image: mariadb
    container_name: db
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - devops

volumes:
  db:

networks:
  devops:
    external: true